#!/bin/bash

ARG=$1
set -e err
set -x

[ "$ARG" != '-i' ] && {
	openssl genrsa -des3 -out server.key 2048
	openssl rsa -in server.key -out server.key.insecure
	mv server.key server.key.secure
	mv server.key.insecure server.key
	openssl req -new -key server.key -out server.csr
	openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
}
[ "$ARG" == '-i' ] && {
	sudo cp server.crt /etc/ssl/certs
	sudo cp server.key /etc/ssl/private
}
