#!/bin/sh
set -e
#echo "checking deps"
#echo "Check for ruby..TBA"

echo updating package list
sudo apt-get update

echo "\nInstalling ruby"
sudo apt-get install ruby-full
echo "done installing ruby"

echo "installing fluentd"
sudo gem install fluentd
echo "installed fluentd"

